[profile.default]
src = "contracts"
test = "forge-tests"
out = "out"
libs = ["lib"]
solc_version = "0.8.10"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "Governance/=./contracts/Governance/",
    "Oracle/=./contracts/Oracle/",
    "TAT/=./contracts/TAT/",
    "Treasure/=./contracts/Treasure/",
    "TCash/=./contracts/TCash/",
    "Crosschain/=./contracts/Crosschain/",
    "TokenLocker/=./contracts/TokenLocker/"
]
